### ISSUE TITLE
Helm chart references wrong secret for metrics-server

### ISSUE THREAD

**Issue by hamishforbes** [actions/actions-runner-controller#2175]
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

0.27.0

### Helm Chart Version

0.22.0

### Deployment Method

Helm

### cert-manager installation

Yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
Chart values:

    actionsMetricsServer:
      enabled: true
      secret:
        enabled: true
      service:
        ports:
        - name: http
          port: 8000
          protocol: TCP
          targetPort: http
      serviceMonitor: true
    authSecret:
      create: false # Manually create 'controller-manager' secret with GH creds
    githubWebhookServer:
      enabled: true
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
      replicaCount: 2
    metrics:
      proxy:
        enabled: false
      serviceMonitor: true
```
```


### To Reproduce

```markdown
Enable metrics-server, check the env vars
```

### Describe the bug

The helm chart is trying to pull Github credentials (`GITHUB_TOKEN`, `GITHUB_APP_ID` etc) from the secret storing the webhook secret rather than the secret storing credentials.

https://github.com/actions/actions-runner-controller/blob/0324658a3fad79237b5da9c21a3ce6f6cc9a4429/charts/actions-runner-controller/templates/actionsmetrics.deployment.yaml#L72-L96

```
> k describe deploy actions-runner-controller-actions-metrics-server | grep GITHUB_APP_ID
      GITHUB_APP_ID:                <set to the key 'github_app_id' in secret 'github-webhook-server'>                 Optional: true

> k describe deploy actions-runner-controller | grep GITHUB_APP_ID
      GITHUB_APP_ID:               <set to the key 'github_app_id' in secret 'controller-manager'>               Optional: true
````

Credentials are in the (default name) `controller-manager` secret, I am not using a webhook secret at all currently so `github-webhook-server` doesn't exist.

```
> k get secret | grep Opaque
controller-manager                                            Opaque                                3      615d
```

The GH client never gets initialised and then we get a segfault when a webhook is received.

```
2023-01-17T21:09:18Z	INFO	GitHub client is not initialized. Runner groups with custom visibility are not supported. If needed, please provide GitHub authentication. This will incur in extra GitHub API calls

2023-01-17T21:09:36Z	INFO	workflowjobmetrics-webhookserver	ok	{"event": "workflow_job", "hookID": "397065108", "delivery": "78d6e540-969b-11ed-90bd-fb42ff6449d0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1344519]

goroutine 64 [running]:
github.com/actions/actions-runner-controller/pkg/actionsmetrics.(*EventReader).fetchAndParseWorkflowJobLogs(0x14ba860?, {0x18c4650?, 0xc00004e040?}, 0xe?)
	github.com/actions/actions-runner-controller/pkg/actionsmetrics/event_reader.go:167 +0x59
github.com/actions/actions-runner-controller/pkg/actionsmetrics.(*EventReader).ProcessWorkflowJobEvent(0xc000590030, {0x18c4650, 0xc00004e040}, {0x152af80?, 0xc00001b590})
	github.com/actions/actions-runner-controller/pkg/actionsmetrics/event_reader.go:99 +0x6e5
github.com/actions/actions-runner-controller/pkg/actionsmetrics.(*EventReader).ProcessWorkflowJobEvents(0xc000590030, {0x18c4650, 0xc00004e040})
	github.com/actions/actions-runner-controller/pkg/actionsmetrics/event_reader.go:44 +0x59
main.main.func1()
	github.com/actions/actions-runner-controller/cmd/actionsmetricsserver/main.go:157 +0x6c
created by main.main
	github.com/actions/actions-runner-controller/cmd/actionsmetricsserver/main.go:154 +0xdef
```

If I manually modify the deployment to reference the correct secret then all works correctly.
I can also set `githubWebhookServer.secret.name` in the chart values, but that will change the secret the webhook server is referencing as well.

### Describe the expected behavior

Should reference the correct secret.
The metrics-server is unique in that it needs both the webhook secret and the github credentials, so probably needs another set of secret related values in the chart?

Probably a couple other improvements that could be made at the same time.
As I understand it the metrics-server *requires* the github client to be working, maybe better to throw an error and exit if the client can't be initialised at startup?

There's no doco for the metrics-server yet? Not that I could find anyway, so taken a bit of faffing around to even get this far!

### Whole Controller Logs

```shell
N/A
```

### Whole Runner Pod Logs

```shell
N/A
```

**Comment by dongho-jung** [comment]
I bumped this issue too. In helm charts README there's actionsMetricsServer.secret.* options but under templates/ it seems there's no such thing thus I can't configure secret which is wrong.

**Comment by Dawnflash** [comment]
Same, I bypassed this by using the same secret for webhook and metrics server (the webhook server only needs the webhook secret key so it works) but it feels hacky.

**Comment by remover** [comment]
> If I manually modify the deployment to reference the correct secret then all works correctly.

@hamishforbes how did you do that?
