### ISSUE TITLE
Intermittent GHA Listener Failures 

### ISSUE THREAD

**Issue by jb-2020** [actions/actions-runner-controller#3682]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Deploy helm charts
Wait for the listener to restart
```

### Describe the bug

Intermittently some of our listener pods will become unresponsive for 15-20 minutes.  This is surfaced as long queue times for Workflows.  This occurs ~4 times a day and usually correlated with load on the GHES server.  It seems to happen in 'waves' impacting roughly ~90% of our listeners. 

Observed behavior:

1. The listener will throw a `context deadline exceeded (Client.Timeout exceeded while awaiting headers)` - this error is repeated 3 times with 5 minute pauses between the events.
2. The listener throws: `read tcp <REDACTED>:41054-><REDACTED>:443: read: connection timed out`
3. One of the following occurs: 
    - The controller restarts the listener pod and it comes back as healthy
    - No error message is thrown and the listener continues on as expected
    - The listener throws: `Message queue token is expired during GetNextMessage, refreshing...` and it continues on as expected.
  
During step 1 the listener is not functional and causes 15-20 minute down times. 

Should this timeout be set to 1 minute?  [Is 5 minutes too long](https://github.com/actions/actions-runner-controller/blob/master/github/actions/client.go#L211)? 

Note: We do not observe any other connectivity issues with our instance of GHES.  We are investigating issues with our connectivity to GHES and the resiliency of the server and compatibility with HTTP long polls.  With that said, I think there may be an opportunity here to make the listeners more resilient to networking blips. 

### Describe the expected behavior

The listener is not restarted by the controller and doesn't become unresponsive for 15-20 minutes.

### Additional Context

```yaml
GHES Version: 3.9
```

### Controller Logs

```shell
Listener logs: https://gist.github.com/jb-2020/13f246a361f039a54733f90f270eeafa

Controller logs: https://gist.github.com/jb-2020/18c6f276fd351e4f09ac894e545258e6
```

### Runner Pod Logs

```shell
N/A
```

**Comment by w7089** [comment]
Listener pods are running after installation at all form after following the official guide

**Comment by jb-2020** [comment]
@Link- / @nikola-jokic any thoughts here?

**Comment by nikola-jokic** [comment]
Hey @jb-2020, can you please confirm you are not experiencing this issue now?

**Comment by nikola-jokic** [comment]
Closing this one, since we have many changes between 0.9.3 and 0.11.0. We can always re-open it!

**Comment by chlunde** [comment]
@nikola-jokic  We've observed this issue for a while, and I finally got a thread dump and tried debuggig this with Claude Code. The explaination seems legit to me, similar to #3682 

**ARC:** v0.13.1 — same code pattern on master (now in `actions/scaleset`).

## What happens

`broker.actions.githubusercontent.com` accepts an HTTP/2 connection but stops sending response headers. Every reconcile that tries to use that connection blocks for 5 minutes (`HTTPClient.Timeout`), retries up to 4 times, then blocks the next reconcile — because HTTP/2 multiplexes onto the same dead conn. Workqueue stalls; no pods created for 15–20 minutes.

## Logs (ARC emits)

```
2026-05-05T13:57:35Z  error  actions-clients  Retryable client error
  method=DELETE
  url=https://broker.actions.githubusercontent.com/rest/_apis/distributedtask/pools/0/agents/130920?api-version=6.0-preview
  error=Delete "...": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

2026-05-05T13:58:57Z  error  actions-clients  Retryable client error
  method=POST
  url=https://broker.actions.githubusercontent.com/rest/_apis/runtime/runnerscalesets/15/generatejitconfig?api-version=6.0-preview
  error=Post "...": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

## Goroutine dump (SIGABRT at 14:01:19 — both goroutines still stuck, same conn `0xc001395a40`)

```
goroutine 356 [select, 4 minutes]:
  net/http.(*http2ClientConn).roundTrip(0xc001395a40, ...)    h2_bundle.go:8680
  net/http.(*Client).do(...)                                  client.go:729
  github.com/hashicorp/go-retryablehttp.(*Client).Do(...)     retryablehttp@v0.7.8/client.go:719
  github/actions.(*Client).Do(...)                            github/actions/client.go:275
  github/actions.(*Client).RemoveRunner(...)                  github/actions/client.go:955
  (*EphemeralRunnerReconciler).deleteRunnerFromService(...)   ephemeralrunner_controller.go:814
  (*EphemeralRunnerReconciler).Reconcile(...)                 ephemeralrunner_controller.go:95

goroutine 357 [select, 2 minutes]:
  net/http.(*http2ClientConn).roundTrip(0xc001395a40, ...)    h2_bundle.go:8680   ← same conn
  net/http.(*Client).do(...)                                  client.go:729
  github.com/hashicorp/go-retryablehttp.(*Client).Do(...)     retryablehttp@v0.7.8/client.go:719
  github/actions.(*Client).Do(...)                            github/actions/client.go:275
  github/actions.(*Client).GenerateJitRunnerConfig(...)       github/actions/client.go:857
  (*EphemeralRunnerReconciler).createRunnerJitConfig(...)     ephemeralrunner_controller.go:621
  (*EphemeralRunnerReconciler).Reconcile(...)                 ephemeralrunner_controller.go:177
```

## Why retryablehttp doesn't bail

`DefaultRetryPolicy` correctly checks `ctx.Err() != nil` — but the reconcile context has no deadline (controller-runtime passes its own ctx straight through), so `ctx.Err()` is always `nil`. The `Client.Timeout` error is a `*url.Error` that doesn't match any of the "don't retry" regexes in `baseRetryPolicy`, so it retries.

## Fix

**1. HTTP/2 PING health check** — `github/actions/client.go` after the transport cast (~line 215):

```go
import "golang.org/x/net/http2"

t2, err := http2.ConfigureTransports(transport)
if err != nil {
    return nil, fmt.Errorf("failed to configure http2 transport: %w", err)
}
t2.ReadIdleTimeout = 30 * time.Second
t2.PingTimeout     = 15 * time.Second
```

Detects and closes dead HTTP/2 connections within ~45s. In-flight streams on the dead conn abort; next request dials fresh.

**2. Reconcile deadline** — `controllers/actions.github.com/ephemeralrunner_controller.go` at top of `Reconcile`:

```go
ctx, cancel := context.WithTimeout(ctx, 60*time.Second)
defer cancel()
```

Caps total time any reconcile can hold a worker. Also makes the existing `retryablehttp` ctx check actually fire.

Same deadline for the EphemeralRunnerSet reconciler.

**Comment by jb-2020** [comment]
@chlunde nice find! I went with the sledge hammer approach by enabling `DisableKeepAlives` in the HTTP transporter which resolved our failures (which admittedly isn't good for ARC or our GHES instance).  @nikola-jokic / @rentziass  should @chlunde finding be reported in `actions/scaleset` these days?
